import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence,motion} from 'framer-motion';
import {Activity,ArrowUpRight,BarChart3,Bell,Building2,Check,ChevronRight,Cloud,Command,Database,FileCheck2,Globe2,Layers3,LayoutDashboard,LockKeyhole,LogOut,Menu,Plus,Search,Settings,ShieldCheck,SlidersHorizontal,Sparkles,ToggleLeft,ToggleRight,Users,WalletCards,X,AlertTriangle} from 'lucide-react';
import './index.css';

const featureSeed=[
 ['Asset Discovery','asset_discovery',true,'Inventory, fingerprinting and scope-aware discovery'],
 ['Exposure Assessment','exposure_assessment',true,'Exposure and vulnerability assessment workflow'],
 ['Risk Intelligence','risk_intelligence',true,'Risk scoring, prioritization and trends'],
 ['Defensive Engine','defensive_engine',true,'Defensive file and posture analysis'],
 ['Deep Web Pentest','deep_web_pentest',false,'Controlled deep-web assessment module'],
 ['Enterprise Reports','enterprise_reports',true,'Executive and technical reporting'],
 ['Infrastructure Vault','infrastructure_vault',true,'Encrypted provider credentials and connectors'],
 ['Community','community',false,'Tenant collaboration and shared intelligence']
];
const tenants=[['Northstar Finance','northstar-finance','Enterprise','Active',184],['Apex Health Systems','apex-health','Professional','Active',76],['Vertex Logistics','vertex-logistics','Enterprise','Pending',0],['BlueOrbit Labs','blueorbit-labs','Starter','Suspended',31]];
const stats=[['MRR','$42.8K','+18.4%'],['Active tenants','184','+12.7%'],['Security assessments','1,284','+24.9%'],['Pending approvals','17','-8.2%']];

function App(){const [section,setSection]=useState('overview');const [mobile,setMobile]=useState(false);const [features,setFeatures]=useState(featureSeed);const [tenantsState,setTenants]=useState(tenants);const nav=[['overview','Overview',LayoutDashboard],['tenants','Tenants',Building2],['subscriptions','Subscriptions',WalletCards],['features','Feature Control',SlidersHorizontal],['leads','Lead Intelligence',Users],['isolation','Isolation',LockKeyhole],['security','Security',ShieldCheck],['settings','Settings',Settings]];
const toggleFeature=(i)=>setFeatures(f=>f.map((x,n)=>n===i?[x[0],x[1],!x[2],x[3]]:x));
return <div className="min-h-screen text-slate-100 grid-bg"><div className="flex min-h-screen">
<aside className={`fixed lg:sticky z-40 inset-y-0 left-0 w-[280px] p-4 transition-transform ${mobile?'translate-x-0':'-translate-x-full lg:translate-x-0'}`}><div className="glass rounded-3xl h-full flex flex-col shadow-glow overflow-hidden"><div className="p-5 border-b border-white/10"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-2xl bg-gradient-to-br from-indigo-500 to-cyan-400 grid place-items-center shadow-lg"><ShieldCheck size={23}/></div><div><div className="font-black tracking-wide">CYBER TERRAFOR</div><div className="text-[10px] text-indigo-300 font-bold tracking-[.2em]">MASTER CONTROL</div></div></div></div><div className="px-3 pt-5 text-[10px] uppercase tracking-[.18em] text-slate-500 font-bold">Platform</div><nav className="p-3 space-y-1 flex-1">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>{setSection(id);setMobile(false)}} className={`w-full flex items-center gap-3 px-3 py-3 rounded-xl text-sm transition ${section===id?'bg-white/10 text-white shadow-inner':'text-slate-400 hover:text-white hover:bg-white/5'}`}><Icon size={17}/><span>{label}</span>{id==='leads'&&<span className="ml-auto text-[10px] bg-indigo-500/20 text-indigo-300 px-2 py-1 rounded-full">24</span>}</button>)}</nav><div className="p-3"><div className="rounded-2xl p-4 bg-gradient-to-br from-indigo-500/15 to-cyan-400/10 border border-indigo-400/10"><div className="flex items-center gap-2 text-xs font-semibold"><Sparkles size={14} className="text-cyan-300"/> Enterprise Cloud</div><p className="text-xs text-slate-500 mt-2">Isolated tenant environments are healthy.</p><div className="mt-3 h-1.5 rounded-full bg-white/5"><div className="h-full w-[92%] rounded-full bg-gradient-to-r from-indigo-500 to-cyan-400"/></div></div></div></div></aside>
<div className="flex-1 min-w-0"><header className="sticky top-0 z-30 px-4 lg:px-8 py-4"><div className="glass rounded-2xl px-4 py-3 flex items-center gap-4"><button className="lg:hidden p-2 rounded-xl hover:bg-white/5" onClick={()=>setMobile(true)}><Menu/></button><div className="hidden md:flex items-center gap-2 text-xs text-slate-500"><Command size={14}/> / Master Admin / <span className="text-slate-300">{nav.find(n=>n[0]===section)?.[1]}</span></div><div className="ml-auto flex items-center gap-2"><div className="hidden sm:flex items-center gap-2 rounded-xl bg-black/20 border border-white/10 px-3 py-2 text-xs text-slate-500"><Search size={14}/> Search workspace</div><button className="p-2.5 rounded-xl bg-white/5 hover:bg-white/10"><Bell size={17}/></button><div className="h-9 w-9 rounded-xl bg-gradient-to-br from-violet-500 to-indigo-600 grid place-items-center font-bold text-sm">FA</div></div></div></header><main className="px-4 lg:px-8 pb-10 max-w-[1600px] mx-auto"><AnimatePresence mode="wait"><motion.div key={section} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.22}}>{section==='overview'&&<Overview stats={stats} tenants={tenantsState}/>} {section==='features'&&<FeatureControl features={features} toggle={toggleFeature}/>} {section==='tenants'&&<Tenants tenants={tenantsState}/>} {section==='subscriptions'&&<Subscriptions tenants={tenantsState} setTenants={setTenants}/>} {section==='leads'&&<Leads/>} {section==='isolation'&&<Isolation tenants={tenantsState}/>} {section==='security'&&<Security/>} {section==='settings'&&<SettingsPage/>}</motion.div></AnimatePresence></main></div></div>{mobile&&<button className="fixed inset-0 bg-black/60 z-30 lg:hidden" onClick={()=>setMobile(false)}><X className="absolute top-5 right-5"/></button>}</div>}

function PageTitle({eyebrow,title,sub,action}){return <div className="flex flex-col md:flex-row md:items-end justify-between gap-5 mb-7"><div><div className="text-[11px] uppercase tracking-[.22em] text-indigo-300 font-bold">{eyebrow}</div><h1 className="text-3xl lg:text-4xl font-black mt-2 tracking-tight">{title}</h1><p className="text-slate-500 mt-2 max-w-2xl">{sub}</p></div>{action}</div>}
function Overview({stats,tenants}){return <><PageTitle eyebrow="Control plane" title="Master Admin Dashboard" sub="One premium command center for subscriptions, tenants, feature flags, security posture and isolated environments." action={<button className="px-4 py-3 rounded-xl bg-white text-slate-900 font-bold text-sm flex items-center gap-2"><Plus size={16}/> Provision tenant</button>}/><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{stats.map(([a,b,c],i)=><div key={a} className="glass rounded-2xl p-5"><div className="flex justify-between text-xs text-slate-500"><span>{a}</span><Activity size={15} className="text-indigo-300"/></div><div className="text-3xl font-black mt-3">{b}</div><div className="text-xs text-emerald-300 mt-2">{c} vs last period</div></div>)}</div><div className="grid xl:grid-cols-[1.6fr_1fr] gap-5 mt-5"><div className="glass rounded-2xl p-5"><div className="flex items-center justify-between mb-5"><div><h2 className="font-bold">Platform activity</h2><p className="text-xs text-slate-500 mt-1">Tenant, subscription and assessment telemetry</p></div><BarChart3 className="text-indigo-300"/></div><div className="h-56 flex items-end gap-3">{[42,55,48,76,61,88,72,94,81,99,91,100].map((v,i)=><motion.div initial={{height:0}} animate={{height:`${v}%`}} transition={{delay:i*.03}} key={i} className="flex-1 rounded-t-lg bg-gradient-to-t from-indigo-600/30 to-cyan-400/70 min-w-2"/> )}</div><div className="flex justify-between text-[10px] text-slate-600 mt-3"><span>Jan</span><span>Dec</span></div></div><div className="glass rounded-2xl p-5"><div className="flex justify-between items-center"><h2 className="font-bold">System health</h2><span className="text-xs text-emerald-300 flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"/> Operational</span></div><div className="space-y-4 mt-5">{[['Core API','99.99%'],['Tenant isolation','100%'],['Database','99.98%'],['Queue workers','99.97%']].map(([a,b])=><div key={a}><div className="flex justify-between text-xs mb-2"><span className="text-slate-400">{a}</span><b>{b}</b></div><div className="h-2 bg-white/5 rounded-full"><div className="h-full w-[99%] rounded-full bg-emerald-400/70"/></div></div>)}</div></div></div><div className="glass rounded-2xl p-5 mt-5"><div className="flex justify-between items-center mb-4"><div><h2 className="font-bold">Recent tenant activity</h2><p className="text-xs text-slate-500 mt-1">Latest provisioning and subscription events</p></div><button className="text-xs text-indigo-300 flex items-center gap-1">View all <ChevronRight size={14}/></button></div><TenantTable tenants={tenants}/></div></>}
function TenantTable({tenants}){return <div className="overflow-auto"><table className="w-full text-sm"><thead className="text-left text-[10px] uppercase tracking-wider text-slate-600"><tr><th className="pb-3">Tenant</th><th>Plan</th><th>Status</th><th>Assets</th><th/></tr></thead><tbody>{tenants.map(t=><tr key={t[1]} className="border-t border-white/5"><td className="py-4"><div className="font-semibold">{t[0]}</div><div className="text-[11px] text-slate-600">{t[1]}.isolated</div></td><td><span className="px-2.5 py-1 rounded-lg bg-white/5 text-xs">{t[2]}</span></td><td><span className={`text-xs ${t[3]==='Active'?'text-emerald-300':t[3]==='Pending'?'text-amber-300':'text-rose-300'}`}>{t[3]}</span></td><td className="text-slate-400">{t[4]}</td><td><ArrowUpRight size={15} className="text-slate-600"/></td></tr>)}</tbody></table></div>}
function FeatureControl({features,toggle}){return <><PageTitle eyebrow="Global governance" title="Feature Control" sub="Turn modules on or off globally or prepare plan-level feature gates without touching the legacy security engine."/><div className="grid md:grid-cols-2 gap-4">{features.map((f,i)=><motion.div layout key={f[1]} className="glass rounded-2xl p-5"><div className="flex items-start gap-4"><div className="h-11 w-11 rounded-xl bg-indigo-500/10 border border-indigo-400/10 grid place-items-center"><Layers3 size={18} className="text-indigo-300"/></div><div className="flex-1"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold">{f[0]}</h3><p className="text-xs text-slate-500 mt-1">{f[3]}</p></div><button onClick={()=>toggle(i)} className="text-slate-300">{f[2]?<ToggleRight size={35} className="text-emerald-300"/>:<ToggleLeft size={35} className="text-slate-600"/>}</button></div><div className="mt-4 flex items-center gap-2 text-[11px]"><span className={`px-2 py-1 rounded-md ${f[2]?'bg-emerald-400/10 text-emerald-300':'bg-slate-400/10 text-slate-500'}`}>{f[2]?'Enabled':'Disabled'}</span><span className="text-slate-600">Global policy</span></div></div></div></motion.div>)}</div></>}
function Tenants({tenants}){return <><PageTitle eyebrow="Tenant registry" title="Isolated Workspaces" sub="Every approved buyer receives a logically isolated pocket with its own tenant identity, policies and workspace boundary."/><div className="glass rounded-2xl p-5"><TenantTable tenants={tenants}/></div></>}
function Subscriptions({tenants,setTenants}){const approve=(idx)=>setTenants(t=>t.map((x,i)=>i===idx?[x[0],x[1],x[2],'Active',x[4]||1]:x));return <><PageTitle eyebrow="Revenue operations" title="Subscriptions & Approvals" sub="Review incoming subscription requests, approve or reject them, then provision an isolated tenant environment."/><div className="grid lg:grid-cols-3 gap-4 mb-5">{[['Pending review','17','Action required'],['Approved today','12','+20%'],['Renewals this month','38','96% retention']].map(x=><div className="glass rounded-2xl p-5" key={x[0]}><div className="text-xs text-slate-500">{x[0]}</div><div className="text-3xl font-black mt-2">{x[1]}</div><div className="text-xs text-indigo-300 mt-1">{x[2]}</div></div>)}</div><div className="space-y-3">{tenants.map((t,i)=><div key={t[1]} className="glass rounded-2xl p-5 flex flex-col md:flex-row md:items-center gap-4"><div className="h-11 w-11 rounded-xl bg-white/5 grid place-items-center"><Building2 size={18}/></div><div className="flex-1"><b>{t[0]}</b><div className="text-xs text-slate-500 mt-1">{t[2]} · requested secure workspace</div></div><span className={`text-xs px-2.5 py-1 rounded-lg ${t[3]==='Pending'?'bg-amber-400/10 text-amber-300':'bg-emerald-400/10 text-emerald-300'}`}>{t[3]}</span>{t[3]==='Pending'?<div className="flex gap-2"><button onClick={()=>approve(i)} className="px-3 py-2 rounded-lg bg-emerald-400/10 text-emerald-300 text-xs font-bold flex items-center gap-1"><Check size={14}/> Approve</button><button className="px-3 py-2 rounded-lg bg-rose-400/10 text-rose-300 text-xs font-bold">Reject</button></div>:<button className="px-3 py-2 rounded-lg bg-white/5 text-xs">Manage</button>}</div>)}</div></>}
function Leads(){return <><PageTitle eyebrow="Growth intelligence" title="Lead Intelligence" sub="Centralized lead capture from landing pages, trial requests, subscription forms and sales channels." action={<button className="px-4 py-3 rounded-xl bg-white text-slate-900 font-bold text-sm flex items-center gap-2"><Plus size={16}/> Add lead</button>}/><div className="glass rounded-2xl p-5 overflow-auto"><table className="w-full text-sm"><thead className="text-left text-[10px] uppercase text-slate-600"><tr><th className="pb-3">Company</th><th>Intent</th><th>Source</th><th>Score</th><th>Next action</th></tr></thead><tbody>{[['Meridian Bank','Enterprise','Website','94','Demo'],['Nova Manufacturing','Professional','Trial','87','Follow-up'],['Helix Group','Enterprise','Partner','82','Proposal'],['Orbit Education','Starter','Campaign','71','Nurture']].map(r=><tr key={r[0]} className="border-t border-white/5"><td className="py-4 font-semibold">{r[0]}</td><td>{r[1]}</td><td className="text-slate-500">{r[2]}</td><td><span className="text-indigo-300 font-bold">{r[3]}</span></td><td><button className="px-3 py-1.5 rounded-lg bg-white/5 text-xs">{r[4]}</button></td></tr>)}</tbody></table></div></>}
function Isolation({tenants}){return <><PageTitle eyebrow="Zero-trust tenancy" title="Isolation Manager" sub="Provision private tenant pockets with dedicated namespace, storage boundary, feature policy and audit scope."/><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{tenants.slice(0,3).map(t=><div key={t[1]} className="glass rounded-2xl p-5"><div className="flex justify-between"><div className="h-11 w-11 rounded-xl bg-cyan-400/10 grid place-items-center"><Cloud className="text-cyan-300" size={18}/></div><span className="text-[10px] px-2 py-1 rounded-md bg-emerald-400/10 text-emerald-300">ISOLATED</span></div><h3 className="font-bold mt-5">{t[0]}</h3><p className="text-xs text-slate-600 mt-1">{t[1]}.isolated</p><div className="grid grid-cols-2 gap-2 mt-5 text-xs">{[['Namespace','Dedicated'],['Storage','Private'],['Audit scope','Tenant'],['Feature policy','Plan']].map(x=><div className="rounded-xl bg-white/[.03] p-3" key={x[0]}><div className="text-slate-600">{x[0]}</div><div className="mt-1 font-semibold">{x[1]}</div></div>)}</div><button className="w-full mt-4 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-xs font-bold">Open control plane</button></div>)}</div></>}
function Security(){return <><PageTitle eyebrow="Trust center" title="Platform Security" sub="Centralized posture for tenant isolation, identity, audit and the unchanged Cyber Terrafor security engine."/><div className="grid md:grid-cols-2 gap-4">{[['Tenant boundary','Verified','Every tenant carries a unique isolation key and namespace.'],['Admin MFA','Enforced','Master administrators require strong authentication.'],['Audit integrity','Healthy','Immutable event trail for subscription and policy actions.'],['Legacy engine','Protected','Core assessment modules remain outside the SaaS presentation layer.']].map(x=><div className="glass rounded-2xl p-5" key={x[0]}><div className="flex items-center gap-3"><div className="h-10 w-10 rounded-xl bg-emerald-400/10 grid place-items-center"><FileCheck2 size={17} className="text-emerald-300"/></div><div><b>{x[0]}</b><div className="text-xs text-emerald-300 mt-1">{x[1]}</div></div></div><p className="text-xs text-slate-500 mt-4">{x[2]}</p></div>)}</div></>}
function SettingsPage(){return <><PageTitle eyebrow="Platform configuration" title="Master Settings" sub="Configure branding, billing policies, environment defaults and platform-wide controls."/><div className="grid lg:grid-cols-2 gap-4">{[['Billing policy','Manual approval enabled'],['Default tenant region','Bangladesh / Asia'],['Lead retention','365 days'],['Session policy','MFA + RBAC']].map(x=><div className="glass rounded-2xl p-5 flex justify-between items-center" key={x[0]}><div><b>{x[0]}</b><p className="text-xs text-slate-500 mt-1">{x[1]}</p></div><Settings size={18} className="text-slate-600"/></div>)}</div></>}

createRoot(document.getElementById('root')).render(<App/>);
